# Memoria disponible para Gradle y codificación del proyecto.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Activa AndroidX y el estilo oficial de Kotlin.
android.useAndroidX=true
kotlin.code.style=official

# Mejora el tiempo de compilación al reutilizar resultados y paralelizar tareas.
org.gradle.caching=true
org.gradle.parallel=true
